### PR TITLE
Developer

### PR DESCRIPTION
**Pull request by BusisiweBusie**
I would like to know if my chatbot is okay

### CODE REVIEW

**Review by ZSLNgwenya — COMMENTED** [review]
Everything looks. Just fix the responsiveness

**Comment by ZSLNgwenya** [comment]
> Everything looks great. Just fix the responsiveness

**Comment by BusisiweBusie** [comment]
> Everything looks. Just fix the responsiveness

alright thank you, will work on it

**Comment by TshekoO** [comment]
> I would like to know if my chatbot is okay

Everything looks good just adjust the size of the chatbot response box then you'll be good to go

**Comment by yayah0613912091** [comment]
it looks great on my side

**Comment by BusisiweBusie** [comment]
so I changed the background of the chatbox and tried to adjust the texts to fit the border radius, can you please check if its fine?   also can you check if the chatbox is responding

**Comment by yayah0613912091** [comment]
looks great well done

**Pull request merged**
